name: Tic Tac Toe Tests

on: [push]  # This workflow runs on every push to the repository

jobs:
  test:
    runs-on: ubuntu-latest  # This workflow runs on Ubuntu virtual machines

    steps:
      - uses: actions/checkout@v3  # Checks out the code from the repository
      - name: Set up Node.js environment
        uses: actions/setup-node@v3  # Sets up a Node.js environment
        with:
          node-version: 16  # You can adjust the Node.js version if needed

      - name: Install dependencies
        run: npm install  # Installs project dependencies (assuming you use npm)

      - name: Run tests
        run: npm test  # Runs the tests defined in your project (replace with your actual test command)

